# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

.run_test: &run_test
  script:
    - rustup --version && rustc --version && cargo --version
    - cargo fmt --all -- --check
    - cargo clippy --workspace --all-targets --all-features --verbose -- -D warnings
    - cargo test --workspace --verbose

# Use cargo to test the project
test:stable:
  <<: *run_test
  before_script:
    - rustup toolchain install stable --component rustfmt clippy

test:beta:
  <<: *run_test
  before_script:
    - rustup default beta
    - rustup toolchain install beta --component rustfmt clippy
